tasks:
  - init: sh sql/database-init.sh
    command: |
      mvn package
      java -jar target/openrqm-server-1.0.0.jar
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8090
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
