# openrqm-server
# Azure DevOps Pipeline for building the openrqm-server project
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2019 Benjamin Schilling

pool:
  vmImage: 'ubuntu-latest'



steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '--batch-mode'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'

- script: |
    sudo apt-get install debhelper maven
    mkdir -p debian-packaging
    rsync -av --exclude='debian-packaging' . debian-packaging/
    cd debian-packaging
    dpkg-buildpackage -uc -us
    cd ..
  displayName: 'Debian packaging'

- task: GithubRelease@0 
  condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development')))
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: benjaminSchilling33
    repositoryName: openrqm/openrqm-server
    action: edit
    tagSource: manual
    tag: $(Build.SourceBranchName)  
    assetUploadMode: replace
    assets: |
        $(Build.Repository.LocalPath)/target/openrqm-server-1.0.0.jar
        $(Build.Repository.LocalPath)/target/openrqm-server-1.0.0-javadoc.jar
        $(Build.Repository.LocalPath)/target/openrqm-server-1.0.0-sources.jar
        $(Build.Repository.LocalPath)/README.md
        $(Build.Repository.LocalPath)/openrqm-server_1.0.0_amd64.deb